[build]
builder = "RAILPACK"

[deploy]
runtime = "V2"
numReplicas = 1
overlapSeconds = 0
drainingSeconds = 60
healthcheckPath = "/health"
sleepApplication = true
useLegacyStacker = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig]

[deploy.multiRegionConfig."europe-west4-drams3a"]
numReplicas = 1
